# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - virtual_joint
    - table_joint
    - link1_joint
    - link2_joint
    - ram_joint
    - wheel1_joint
    - wheel2_joint
    - wheel3_joint
    - wheel4_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - table_joint
      - link1_joint
      - link2_joint
      - ram_joint
      
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - table_joint
    - link1_joint
    - link2_joint
    - ram_joint
  gains:
    table_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ram_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1